import datetime

TIME_INTERVAL = datetime.timedelta(minutes=1)

FOOD_DECREASE = 1
CLEANLINESS_DECREASE = 1

FROG_PRICE = 500

MAX_CLEANLINESS = 100
MAX_FOOD = 100
MAX_MONEY = 100
PRIMARY_INCOME = 2
SECONDARY_INCOME = 1

CLEANLINESS_INCREASE = MAX_CLEANLINESS
FOOD_INCREASE = MAX_FOOD
